#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsoup
Version  : 1.10.2
Release  : 4
URL      : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
Source0  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
Source1  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom
Source2  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.jar
Source3  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom
Source4  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.jar
Source5  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.pom
Source6  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar
Source7  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom
Source8  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar
Source9  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-jsoup-data = %{version}-%{release}
Requires: mvn-jsoup-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
jsoup: Java HTML parser that makes sense of real-world HTML soup.
jsoup is a Java library for working with real-world HTML. It provides a very convenient API for extracting and manipulating data, using the best of DOM, CSS, and jquery-like methods.

%package data
Summary: data components for the mvn-jsoup package.
Group: Data

%description data
data components for the mvn-jsoup package.


%package license
Summary: license components for the mvn-jsoup package.
Group: Default

%description license
license components for the mvn-jsoup package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jsoup
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-jsoup/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.6.3/jsoup-1.6.3.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jsoup/LICENSE
