#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsoup
Version  : 1.10.2
Release  : 1
URL      : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
Source0  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
Source1  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom
Source2  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar
Source3  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom
Source4  : https://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-jsoup-data = %{version}-%{release}

%description
jsoup: Java HTML parser that makes sense of real-world HTML soup.
jsoup is a Java library for working with real-world HTML. It provides a very convenient API for extracting and manipulating data, using the best of DOM, CSS, and jquery-like methods.

%package data
Summary: data components for the mvn-jsoup package.
Group: Data

%description data
data components for the mvn-jsoup package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom
/usr/share/java/.m2/repository/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.pom
